sfa_crm_fc/crm/urls.py
from django.urls import path
from .views import index,alert_index,alert_search,contact_index,contact_search

app_name="crm"
urlpatterns = [
    path('', index, name="index"),
    path('alert_index/', alert_index, name="alert_index"),
    path('alert_search/', alert_search, name="alert_search"),
    path('contact_index/', contact_index, name="contact_index"),
    path('contact_search/', contact_search, name="contact_search"),
]

sfa_crm_fc/sfa/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import index_api,index,sfa_search,open_eye,show_hidden,cus_modal_show,cus_modal_bikou,cus_modal_bot,cus_modal_list_click, \
                    cus_modal_bot_del,cus_modal_sort,modal_alert_check,hidden_index,hidden_search,hidden_to_show,\
                    sfa_page_prev,sfa_page_first,sfa_page_next,sfa_page_last,member_index,member_add,free
                    



app_name="sfa"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='sfa/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', index, name="index"),
    path('index_api/', index_api, name="index_api"),
    path('sfa_search/', sfa_search, name="sfa_search"),
    path('sfa_page_prev/', sfa_page_prev, name="sfa_page_prev"),
    path('sfa_page_first/', sfa_page_first, name="sfa_page_first"),
    path('sfa_page_next/', sfa_page_next, name="sfa_page_next"),
    path('sfa_page_last/', sfa_page_last, name="sfa_page_last"),
    path('open_eye/', open_eye, name="open_eye"),
    path('show_hidden/', show_hidden, name="show_hidden"),
    path('cus_modal_show/', cus_modal_show, name="cus_modal_show"),
    path('cus_modal_bikou/', cus_modal_bikou, name="cus_modal_bikou"),
    path('cus_modal_bot/', cus_modal_bot, name="cus_modal_bot"),
    path('cus_modal_bot_del/', cus_modal_bot_del, name="cus_modal_bot_del"),
    path('cus_modal_list_click/', cus_modal_list_click, name="cus_modal_list_click"),
    path('cus_modal_sort/', cus_modal_sort, name="cus_modal_sort"),
    path('modal_alert_check/', modal_alert_check, name="modal_alert_check"),
    path('hidden_index/', hidden_index, name="hidden_index"),
    path('hidden_search/', hidden_search, name="hidden_search"),
    path('hidden_to_show/', hidden_to_show, name="hidden_to_show"),
    path('member_index/', member_index, name="member_index"),
    path('member_add/', member_add, name="member_add"),
    path('free/', free, name="free"),
]

sfa_crm_fc/sfa_crm_fc/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("sfa.urls")),
    path('crm/', include("crm.urls")),
]

sfa_crm_fc/sfa/models.py
from django.db import models

class Sfa_data(models.Model):
    mitsu_id=models.CharField("見積ID",max_length=255,unique=True)
    mitsu_num=models.CharField("見積番号",max_length=255)
    mitsu_ver=models.CharField("見積バージョン",max_length=255)
    mitsu_url=models.CharField("見積URL",max_length=255,blank=True,null=True)
    status=models.CharField("ステータス",max_length=255,blank=True,null=True)
    order_kubun=models.CharField("注文区分",max_length=255,blank=True,null=True)
    nouhin_kigen=models.CharField("納品期限日",max_length=255,blank=True,null=True)
    nouhin_shitei=models.CharField("納品指定日",max_length=255,blank=True,null=True)
    make_day=models.CharField("見積作成日",max_length=255,blank=True)
    update_day=models.CharField("更新日",max_length=255,blank=True)
    juchu_day=models.CharField("受注日",max_length=255,blank=True,null=True)
    hassou_day=models.CharField("発送完了日",max_length=255,blank=True,null=True)
    cus_id=models.CharField("顧客ID",max_length=255,blank=True,null=True)
    sei=models.CharField("姓",max_length=255,blank=True,null=True)
    mei=models.CharField("名",max_length=255,blank=True,null=True)
    com=models.CharField("会社名",max_length=255,blank=True,null=True)
    money=models.IntegerField("金額",blank=True,null=True)
    busho_id=models.CharField("部署ID",max_length=255)
    tantou_id=models.CharField("担当ID",max_length=255)
    show=models.IntegerField("案件表示",default=0)
    eye=models.IntegerField("オープン表示",default=0)
    hidden_day=models.CharField("非表示日時",max_length=255,blank=True,default="")
    s_status=models.CharField("s_ステータス",max_length=255,blank=True,null=True)

    def __str__(self):
        return self.mitsu_id
    
    # show（案件表示） 0:表示　1：非表示
    # eye（オープン表示） 0:表示　1：非表示




class Member(models.Model):
    busho=models.CharField("部署",max_length=255,blank=True,null=True)
    busho_id=models.CharField("部署ID",max_length=255,blank=True,null=True)
    tantou=models.CharField("担当",max_length=255,blank=True,null=True)
    tantou_id=models.CharField("担当ID",max_length=255,blank=True,null=True)
    last_api=models.CharField("最終API接続",max_length=255,blank=True)

    def __str__(self):
        return self.tantou_id

sfa_crm_fc/sfa/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from .models import Sfa_data,Member
from crm.models import Customer,Crm_action
import json
import requests
from datetime import date
import datetime
from django_pandas.io import read_frame
from django.contrib.auth.decorators import login_required



# APIデータ取得
@login_required
def index_api(request):
    tantou_id=request.session["tantou_id"]

    if tantou_id != "":
        
        # 操作者
        sousa_time=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        sousa_busho=Member.objects.get(tantou_id=tantou_id).busho
        sousa_tantou=Member.objects.get(tantou_id=tantou_id).tantou
        print(sousa_time,sousa_busho,sousa_tantou,"■ API接続")


        last_api=Member.objects.get(tantou_id=tantou_id).last_api
        url="https://core-sys.p1-intl.co.jp/p1web/v1/estimations/?handledById=" + tantou_id + "&updatedAtFrom=" + last_api
        res=requests.get(url)
        res=res.json()
        res=res["estimations"]
        for i in res:
            ins=Sfa_data.objects.filter(mitsu_id=i["id"])

            # 初回のデータ取得は外しておく（運用開始後は必要）
            if (ins.count()==0 and i["status"]=="終了") or i["customerId"]==None:
                continue

            # # 初回使用のコード（運用開始後はコメントアウト）
            # if i["customerId"]==None:
            #     continue
            
            
            # ------------------------
            # 案件
            # ------------------------
            Sfa_data.objects.update_or_create(
            mitsu_id=i["id"],
            defaults={
                "mitsu_id":i["id"],
                "mitsu_num":i["number"],
                "mitsu_ver":i["version"],
                "mitsu_url":i["estimationPageUrl"],
                "order_kubun":i["orderType"],
                "nouhin_kigen":i["deliveryLimitDate"],
                "nouhin_shitei":i["deliveryAppointedDate"],
                "make_day":i["createdAt"],
                "update_day":i["updatedAt"],
                "juchu_day":i["orderReceivedDate"],
                "hassou_day":i["shippedDate"],
                "cus_id":i["customerId"],
                "sei":i["ordererNameLast"],
                "mei":i["ordererNameFirst"],
                "com":i["ordererCorporateName"],
                "money":i["totalPrice"],
                "busho_id":i["handledDepartmentId"],
                "tantou_id":i["handledById"],
                "eye":0,
                }
            )
            # ステータス
            d={"見積中":"未","見積送信":"見","イメージ":"イ","受注":"受","発送完了":"発","キャンセル":"キ","終了":"終","保留":"保","":""}
            ins=Sfa_data.objects.get(mitsu_id=i["id"])
            ins.status=i["status"]
            ins.s_status=d[i["status"]]
            ins.save()


            # ------------------------
            # 顧客
            # ------------------------
            url2="https://core-sys.p1-intl.co.jp/p1web/v1/customers/" + str(i["customerId"])
            res2=requests.get(url2)
            res2=res2.json()

            tel_search=None
            if res2["tel"] != None:
                tel_search=res2["tel"].replace("-","")
            tel_mob_search=None
            if res2["mobilePhone"] != None:
                tel_mob_search=res2["mobilePhone"].replace("-","")
            
            try:
                ins=Customer.objects.get(cus_id=i["customerId"])
                update_last_day=ins.update_last_day
                update_last_num=ins.update_last_num
                update_last_ver=ins.update_last_ver
                if i["updatedAt"]>update_last_day:
                    update_last_day=i["updatedAt"]
                    update_last_num=i["number"]
                    update_last_ver=i["version"]
                else:
                    update_last_day=update_last_day
                    update_last_num=update_last_num
                    update_last_ver=update_last_ver
            except:
                update_last_day=i["updatedAt"]
                update_last_num=i["number"]
                update_last_ver=i["version"]
 
            Customer.objects.update_or_create(
            cus_id=res2["id"],
            defaults={
                "cus_id":res2["id"],
                "cus_url":res2["customerMstPageUrl"],
                "cus_touroku":res2["createdAt"],
                "com":res2["corporateName"],
                "com_busho":res2["departmentName"],
                "sei":res2["nameLast"],
                "mei":res2["nameFirst"],
                "pref":res2["prefecture"],
                "city":res2["city"],
                "address_1":res2["address1"],
                "address_2":res2["address2"],
                "tel":res2["tel"],
                "tel_search":tel_search,
                "tel_mob":res2["mobilePhone"],
                "tel_mob_search":tel_mob_search,
                "mail":res2["contactEmail"],
                "juchu_all":res2["totalReceivedOrders"],
                "juchu_money":res2["totalReceivedOrdersPrice"],
                "update_last_day":update_last_day,
                "update_last_num":update_last_num,
                "update_last_ver":update_last_ver,
                }
            )

        # API取得日時
        ins=Member.objects.get(tantou_id=tantou_id)
        ins.last_api=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ins.save()

    return redirect("sfa:index")


# TOPページ表示
@login_required
def index(request):
    if "busho_id" not in request.session:
        request.session["busho_id"]=""
    if "tantou_id" not in request.session:
        request.session["tantou_id"]=""
    if "modal_sort" not in request.session:
        request.session["modal_sort"]="1"

    if "search" not in request.session:
        request.session["search"]={}
    if "com" not in request.session["search"]:
        request.session["search"]["com"]=""
    if "cus_sei" not in request.session["search"]:
        request.session["search"]["cus_sei"]=""
    if "cus_mei" not in request.session["search"]:
        request.session["search"]["cus_mei"]=""
    if "mitsu_num" not in request.session["search"]:
        request.session["search"]["mitsu_num"]=""
    if "page_num" not in request.session["search"]:
        request.session["search"]["page_num"]=1
    if "all_page_num" not in request.session["search"]:
        request.session["search"]["all_page_num"]=""
    
    
    ses=request.session["search"]
    
    # ユーザー情報
    busho_id=request.user.username
    tantou_id=request.session["tantou_id"]
    busho_name=Member.objects.filter(busho_id=busho_id)[0].busho
    request.session["busho_id"]=busho_id

    # フィルター
    fil={}
    fil["show"]=0
    fil["tantou_id"]=tantou_id
    
    flag=False
    if ses["com"] != "":
        fil["com__contains"]=ses["com"].strip()
        flag=True
    if ses["cus_sei"] != "":
        fil["sei__contains"]=ses["cus_sei"].strip()
        flag=True
    if ses["cus_mei"] != "":
        flag=True
        fil["mei__contains"]=ses["cus_mei"].strip()
    if ses["mitsu_num"] != "":
        flag=True
        fil["mitsu_num"]=ses["mitsu_num"].strip()
    
    ins=Sfa_data.objects.filter(**fil)
    sfa_list=[]
    alert_all=0

    if tantou_id != "":
        # 検索なし
        if flag==False:
            df=read_frame(Sfa_data.objects.filter(tantou_id=tantou_id))
        # 検索あり
        else:
            df=read_frame(ins.filter(tantou_id=tantou_id))

        today=str(date.today())
        alert_list=list(Crm_action.objects.filter(type=6,alert_check=0,day__lte=today).values_list("cus_id",flat=True).order_by("cus_id").distinct())
        alert_set=list(Crm_action.objects.filter(type=6,alert_check=0,day__gt=today).values_list("cus_id",flat=True).order_by("cus_id").distinct())
        df["alert"]=df["cus_id"].isin(alert_list)

        df.sort_values(by=["alert","update_day"],ascending=[False,False],inplace=True)
        df.drop_duplicates("cus_id",inplace=True)
        parent_list=df["cus_id"].to_list()
        
        for i in parent_list:
            ins_parent=list(Customer.objects.filter(cus_id=i).values())[0]
            ins_child=list(ins.filter(cus_id=i).values().order_by("make_day").reverse())

            # ステータス
            st_list=["未","見","イ","受","発","終"]
            st_dic={}
            for h in st_list:
                st_dic[h]=ins.filter(cus_id=i,s_status=h).count()
            ins_parent["status_count"]=st_dic

            # アラート発生
            if i in alert_list:
                ins_parent["alert"]=1
                alert_all +=1
            else:
                ins_parent["alert"]=0

            # アラート設定中
            if i in alert_set:
                ins_parent["alert_set"]=1
            else:
                ins_parent["alert_set"]=0

            # オープン
            ins_parent["eye_count_0"]=ins.filter(cus_id=i,eye=0).count()
            ins_parent["eye_count_1"]=ins.filter(cus_id=i,eye=1).count()

            dic={"parent":ins_parent,"child":ins_child}
            sfa_list.append(dic)

    # ページネーション
    result=len(sfa_list)
    if result == 0:
        all_num = 1
    elif result % 30 == 0:
        all_num = result / 30
    else:
        all_num = result // 30 + 1
    all_num=int(all_num)
    request.session["search"]["all_page_num"]=all_num
    num=ses["page_num"]
    if all_num==1:
        num=1
        request.session["search"]["page_num"]=1

    sfa_list=sfa_list[(num-1)*30 : num*30]

    # その他情報
    tantou_list=Member.objects.filter(busho_id=busho_id).order_by("tantou_id")
    modal_sort=request.session["modal_sort"]

    # アクティブ担当
    if tantou_id=="":
        act_user="担当者が未設定です"
    else:
        act_user=Member.objects.get(tantou_id=tantou_id).tantou

    params={
        "tantou_id":tantou_id,
        "sfa_list":sfa_list,
        "busho_name":busho_name,
        "tantou_list":tantou_list,
        "ses":ses,
        "modal_sort":modal_sort,
        "alert_all":alert_all,
        "num":num,
        "all_num":all_num,
        "act_user":act_user,
    }
    return render(request,"sfa/index.html",params)

sfa_crm_fc/sfa/templates/sfa/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>メニュー</title>

</head>
<body>

    <div class="flex3" style="align-items: center;">
        <div class="flex">
            <div>
                <a href="https://core-sys.p1-intl.co.jp/login/" target="_blank"><img src="{% static 'logo.png' %}"></a>
            </div>
            <div style="margin-left: 30px;">
                <a href="{% url 'sfa:index' %}"><button class="btn btn-outline-dark"><i class="bi bi-clipboard-check"></i> 案件管理一覧</button></a>
            </div>
            <div style="margin-left: 30px;">
                {% if act_user != "担当者が未設定です" %}
                <a href="{% url 'crm:alert_index' %}"><button class="btn btn-outline-dark"><i class="bi bi-alarm"></i> アラート設定表</button></a>
                {% endif %}
            </div>
            <div style="margin-left: 30px;">
                {% if act_user != "担当者が未設定です" %}
                <a href="{% url 'crm:contact_index' %}"><button class="btn btn-outline-dark"><i class="bi bi-person-circle"></i> 顧客最終履歴</button></a>
                {% endif %}
            </div>
            <div style="margin-left: 30px;">
                {% if act_user != "担当者が未設定です" %}
                <a href="{% url 'sfa:hidden_index' %}"><button class="btn btn-outline-dark"><i class="bi bi-x-square"></i> 非表示一覧</button></a>
                {% endif %}
            </div>
        </div>
        <div class="flex" style="align-items: end;">
            <div title="ログアウト">
                <form action="{% url 'sfa:logout' %}" method="post">{% csrf_token %}
                    <button class="btn" type="submit"><img src="{% static 'whale.gif' %}"></button>
                </form>
            </div>
            <div>{{act_user}}</div>
        </div>
    </div>

</body>
</html>

sfa_crm_fc/sfa/templates/sfa/modal_script.html
<script>

    // 詳細モーダル
    $("#modal_cus").on("show.bs.modal", function (event) {
        var item=document.getElementsByName("cus_list");
        for (var i=0; i<item.length; i++){
            item[i].addEventListener("click",function(){
                cus_id=this.id.replace("modal_","");
                modal_all_clear()
                $.ajax({
                    'url': '{% url "sfa:cus_modal_show" %}',
                    'type': 'POST',
                    'data': {"cus_id":cus_id},
                    'dataType': 'json'
                })
                .done(function(response){
                    res=response.cus_info;
                    res2=response.res_det;
                    res3=response.alert;

                    var pref=res.pref??"";
                    var city=res.city??"";
                    var address_1=res.address_1??"";
                    var address_2=res.address_2??"";
                    var sei=res.sei??"";
                    var mei=res.mei??"";

                    document.getElementById("modal_cus_id").innerText=cus_id;
                    document.getElementById("modal_cus_url").innerHTML="<a href='" + res.cus_url + "' target='_blank'>" +
                        "<span style='color: #ff8484;'><i class='bi bi-box-arrow-up-right'></i></span></a>";
                    document.getElementById("modal_com").innerText=res.com;
                    document.getElementById("modal_busho").innerText=res.com_busho;
                    document.getElementById("modal_cus_name").innerText=sei + mei;
                    document.getElementById("modal_address").innerText=pref + city + address_1 + address_2
                    document.getElementById("modal_tel").innerText=res.tel;
                    document.getElementById("modal_mob").innerText=res.tel_mob;
                    document.getElementById("modal_mail").innerText=res.mail;
                    document.getElementById("modal_touroku").innerText=res.cus_touroku;
                    document.getElementById("modal_est_last").innerHTML=res.update_last_day +
                        "<span style='font-size:0.9em; margin-left:10px';>（ <a href='" + res.est_last_url + "' target='_blank'>" +
                        "<span style='color: #008b8b;'><i class='bi bi-box-arrow-up-right'></i></span></a> " +
                        res.update_last_num + "-" + res.update_last_ver + "　" + res.est_last_status + " ）</span>";
                    document.getElementById("modal_bikou").value=res.remark;

                    if (res3.set == 1){
                        document.getElementById("modal_alert_show").style.display="flex";
                        document.getElementById("modal_alert_text").innerText=res3.text;
                        document.getElementById("modal_alert_num").innerText=res3.act_id;
                        document.getElementById("modal_header").style.backgroundColor="#ffcccc";                            
                    };
                    
                    modal_act_list(res2);
                    modal_list_click();

                })
            },false)
        };
    });


    // モーダル備考_決定ボタン
    document.getElementById("modal_btn_bikou").addEventListener("click",function(){
        var cus_id=document.getElementById("modal_cus_id").innerText;
        var bikou=document.getElementById("modal_bikou").value;
        $.ajax({
            'url': '{% url "sfa:cus_modal_bikou" %}',
            'type': 'POST',
            'data': {
                "cus_id":cus_id,
                "bikou":bikou,
            },
            'dataType': 'json'
        })
        .done(function(response){
            window.alert("更新しました！");
        })
    })


    // モーダルbot_決定ボタン
    var icons=document.getElementsByName("icons");
    for (var i=0; i<icons.length; i++){
        icons[i].addEventListener("click",function(){
            var num=this.id.replace("icon_","");
            document.getElementById("modal_bot_type").value=num;
        })
    }


    // モーダルbot_決定ボタン
    document.getElementById("modal_btn_bot").addEventListener("click",function(){
        if (document.getElementById("modal_bot_type").value == 0){
            window.alert("種類を選択してください！");
            return
        }
        $.ajax({
            'url': '{% url "sfa:cus_modal_bot" %}',
            'type': 'POST',
            'data': {
                "act_id":document.getElementById("act_id").innerText,
                "cus_id":document.getElementById("modal_cus_id").innerText,
                "day":document.getElementById("modal_bot_day").value,
                "type":document.getElementById("modal_bot_type").value,
                "text":document.getElementById("modal_bot_text").value,
            },
            'dataType': 'json'
        })
        .done(function(response){
            res2=response.res_det;
            if (res2 == "error"){
                window.alert("環境依存文字が含まれています！");
            } else {
                modal_bot_clear();
                modal_act_list(res2);
                modal_list_click();
            }
        })
    })
    

    // モーダルbot_新規作成
    document.getElementById("modal_btn_bot_new").addEventListener("click",function(){
        modal_bot_clear();
    })


    // モーダルbot_削除
    document.getElementById("modal_btn_bot_del").addEventListener("click",function(){
        var act_id=document.getElementById("act_id").innerText;
        var cus_id=document.getElementById("modal_cus_id").innerText;
        if (act_id == ""){
            window.alert("削除する対象を選択してください！");
            return
        }
        var ans =confirm("本当に削除しますか？");
        if (ans == false){
            return
        }
        $.ajax({
            'url': '{% url "sfa:cus_modal_bot_del" %}',
            'type': 'POST',
            'data': {
                "act_id":act_id,
                "cus_id":cus_id,
            },
            'dataType': 'json'
        })
        .done(function(response){
            res2=response.res_det;
            modal_bot_clear();
            modal_act_list(res2);
            modal_list_click();
        })
    })


    // モーダルの表示順
    var mo_sort = document.getElementById("modal_sort");
    mo_sort.addEventListener("change",function(){
        $.ajax({
            'url': '{% url "sfa:cus_modal_sort" %}',
            'type': 'POST',
            'data': {
                "jun":mo_sort.value,
                "cus_id":document.getElementById("modal_cus_id").innerText,
            },
            'dataType': 'json'
        })
        .done(function(response){
            res2=response.res_det;
            modal_act_list(res2);
            modal_list_click();
        })
    })


    // モーダル_アラート解除
    document.getElementById("modal_alert_check").addEventListener("click",function(){
        $.ajax({
                'url': '{% url "sfa:modal_alert_check" %}',
                'type': 'POST',
                'data': {
                    "alert_num":document.getElementById("modal_alert_num").innerText
                },
                'dataType': 'json'
            })
            .done(function(response){
                document.getElementById("modal_alert_show").style.display="none";
                document.getElementById("modal_alert_num").innerText="";
                document.getElementById("modal_alert_text").innerText="";
                document.getElementById("modal_header").style.backgroundColor=""; 
            })
    });


    // モーダル終了
    btns=document.getElementsByName("modal_btn_close");
    for (var i=0;i<btns.length;i++){
        btns[i].addEventListener("click",function(){
            window.location.reload();
        })
    };


    // FUNC モーダル全クリア
    function modal_all_clear(){
        var now = new Date();
        document.getElementById("modal_cus_id").innerText="";
        document.getElementById("modal_com").innerText="";
        document.getElementById("modal_busho").innerText="";
        document.getElementById("modal_cus_name").innerText="";
        document.getElementById("modal_address").innerText=""
        document.getElementById("modal_tel").innerText="";
        document.getElementById("modal_mob").innerText="";
        document.getElementById("modal_mail").innerText="";
        document.getElementById("modal_touroku").innerText="";
        document.getElementById("modal_bikou").value="";
        document.getElementById("modal_bot_type").value="0";
        document.getElementById("modal_bot_day").value=now.toLocaleDateString('sv-SE');
        document.getElementById("modal_bot_text").value="";
        document.getElementById("act_id").innerText="";
        document.getElementById("modal_cus_action").innerHTML=""
        document.getElementById("modal_alert_show").style.display="none";
        document.getElementById("modal_alert_text").innerText="";
        document.getElementById("modal_alert_num").innerText="";
        document.getElementById("modal_header").style.backgroundColor=""; 
    }


    // FUNC モーダルbot_クリア
    function modal_bot_clear(){
        var now = new Date();
        document.getElementById("modal_bot_type").value="0";
        document.getElementById("modal_bot_day").value=now.toLocaleDateString('sv-SE');
        document.getElementById("modal_bot_text").value="";
        document.getElementById("act_id").innerText="";
    }


    // FUNC モーダル履歴リスト
    function modal_act_list(res2){
        var str = "";
        var last_str = "";
        for (var i of res2){
            if (i.kubun == "est"){
                str="<div class='flex'>" +
                    "<div>" + i.day + "</div>" + 
                    "<div style='margin-left: 20px;'>" + i.est_num + "</div>" +
                    "<div style='margin-left: 20px;'>" + i.status + "</div>" +
                    "<div style='margin-left: 20px;'>" + i.money.toLocaleString() + "円</div>" +
                    "<div style='margin-left: 10px; font-size: 0.9em'>（"  + i.tantou + "）</div>" +
                    "</div>";
            } else {
                var icon = "";
                var text = "";
                // アイコン
                if (i.type == 1){
                    icon="<span style='color: blue; font-weight: bold;'><i class='bi bi-telephone-forward-fill'></i></span>";
                } else if (i.type == 2){
                    icon="<span style='color: #ff9900; font-weight: bold;'><i class='bi bi-envelope-fill'></i></span>";
                } else if (i.type == 3){
                    icon="<span style='color: #646565; font-weight: bold;'><i class='bi bi-clipboard-fill'></i></span>";
                } else if (i.type == 4){
                    icon="<span style='color: #ff3502; font-weight: bold;'><i class='bi bi-shop'></i></span>";
                } else if (i.type == 5){
                    icon="<span style='color: #00c2b8; font-weight: bold;'><i class='bi bi-people-fill'></i></span>";
                } else if (i.type == 6){
                    icon="<span style='color: red; font-weight: bold;'><i class='bi bi-bell-fill'></i></span>";
                };
                text=i.text;
                str="<div class='flex'>" +
                    "<div>" + i.day + "</div>" +
                    "<div style='margin-left: 10px;'>" + icon + "</div>" +
                    "<div style='margin-left: 10px;'>" + text + "</div>" +
                    "</div>";
            };
            
            // カード形式
            if (i.kubun == "est"){
                if (i.status == "見積送信"){
                    str = "<div class='main_0 main_1'>" + str + "</div>";
                } else if (i.status == "イメージ"){
                    str = "<div class='main_0 main_2'>" + str + "</div>";
                } else if (i.status == "受注"){
                    str = "<div class='main_0 main_3'>" + str + "</div>";
                } else if (i.status == "発送完了"){
                    str = "<div class='main_0 main_4'>" + str + "</div>";
                } else if (i.status == "終了"){
                    str = "<div class='main_0 main_5'>" + str + "</div>";
                }
            } else {
                str = "<div class='main_0 main_all' name='act_list' id='" + i.act_id + "'>" + str + "</div>";
            };

            last_str = last_str + str;
        };
        document.getElementById("modal_cus_action").innerHTML=last_str;
    }


    // FUNC モーダル_リストクリック
    function modal_list_click(){
        var item=document.getElementsByName("act_list");
        for (var i=0; i<item.length; i++){
            item[i].addEventListener("click",function(){
                document.getElementById("act_id").innerText=this.id;
                $.ajax({
                    'url': '{% url "sfa:cus_modal_list_click" %}',
                    'type': 'POST',
                    'data': {"act_id":this.id},
                    'dataType': 'json'
                })
                .done(function(response){
                    res=response.res;
                    document.getElementById("modal_bot_day").value=res.day;
                    document.getElementById("modal_bot_type").value=res.type;
                    document.getElementById("modal_bot_text").value=res.text;
                })
            },false)
        };
    }

</script>


<!-- モーダル用 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>