sfa_crm_fc/crm/urls.py
from django.urls import path
from .views import index,alert_index,alert_search,contact_index,contact_search

app_name="crm"
urlpatterns = [
    path('', index, name="index"),
    path('alert_index/', alert_index, name="alert_index"),
    path('alert_search/', alert_search, name="alert_search"),
    path('contact_index/', contact_index, name="contact_index"),
    path('contact_search/', contact_search, name="contact_search"),
]

sfa_crm_fc/sfa_crm_fc/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("sfa.urls")),
    path('crm/', include("crm.urls")),
]

sfa_crm_fc/crm/models.py
from django.db import models

class Customer(models.Model):
    cus_id=models.CharField("顧客ID",max_length=10,unique=True)
    cus_url=models.CharField("顧客URL",max_length=255,blank=True,null=True)
    cus_touroku=models.CharField("顧客登録日",max_length=255,blank=True,null=True)
    com=models.CharField("会社名",max_length=255,blank=True,null=True)
    com_busho=models.CharField("部課名",max_length=255,blank=True,null=True)
    sei=models.CharField("姓",max_length=255,blank=True,null=True)
    mei=models.CharField("名",max_length=255,blank=True,null=True)
    pref=models.CharField("都道府県",max_length=255,blank=True,null=True)
    city=models.CharField("市区町村",max_length=255,blank=True,null=True)
    address_1=models.CharField("番地",max_length=255,blank=True,null=True)
    address_2=models.CharField("建物名",max_length=255,blank=True,null=True)
    tel=models.CharField("電話番号",max_length=255,blank=True,null=True)
    tel_search=models.CharField("電話番号_検索",max_length=255,blank=True,null=True)
    tel_mob=models.CharField("携帯番号",max_length=255,blank=True,null=True)
    tel_mob_search=models.CharField("携帯番号_検索",max_length=255,blank=True,null=True)
    mail=models.CharField("メール",max_length=255,blank=True,null=True)
    juchu_all=models.IntegerField("受注総数",default=0)
    juchu_money=models.BigIntegerField("受注総金額",default=0)
    update_last_day=models.CharField("最終更新日",max_length=255,blank=True,null=True)
    update_last_num=models.CharField("最終更新_見積番号",max_length=255,blank=True,null=True)
    update_last_ver=models.CharField("最終更新_バージョン",max_length=255,blank=True,null=True)

    def __str__(self):
        return self.cus_id
    


class Crm_action(models.Model):
    act_id=models.AutoField("行動ID",primary_key=True)
    cus_id=models.CharField("顧客ID",max_length=10)
    tantou_id=models.CharField("担当ID",max_length=10)
    day=models.CharField("日付",max_length=10)
    type=models.IntegerField("種類",null=False)
    text=models.TextField("内容",blank=True)
    alert_check=models.IntegerField("アラート",default=0)

    def __str__(self):
        return self.cus_id
    
    # type（種類） 1:TEL　 2：メール　 3：メモ　4：来店　5：外商　6：アラート
           

sfa_crm_fc/crm/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect
from .models import Customer,Crm_action
from sfa.models import Sfa_data
from sfa.models import Member
import datetime
import calendar
import jpholiday
from django_pandas.io import read_frame
import json
import requests
from django.contrib.auth.decorators import login_required
from django.db.models import Max


def index(request):
    return render(request,"crm/index.html")


# アラート設定表
@login_required
def alert_index(request):
    if "alert_month" not in request.session:
        request.session["alert_month"]=datetime.datetime.now().strftime("%Y-%m")

    alert_month=request.session["alert_month"]
    alert_dic=make_dic(alert_month)

    tantou_id=request.session["tantou_id"]
    ins=Crm_action.objects.filter(tantou_id=tantou_id,type=6)
    for i in ins:
        if str(i.day[:7])==alert_month:
            cus=list(Customer.objects.filter(cus_id=i.cus_id).values())[0]
            dic={"text":i.text,"check":i.alert_check,"cus":cus}
            alert_dic[i.day]["text_all"].append(dic)
    
    # 操作者
    sousa_time=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    sousa_busho=Member.objects.get(tantou_id=tantou_id).busho
    sousa_tantou=Member.objects.get(tantou_id=tantou_id).tantou
    act_user=Member.objects.get(tantou_id=tantou_id).tantou
    print(sousa_time,sousa_busho,sousa_tantou,"■ アラート設定表")

    params={
        "alert_month":alert_month,
        "act_user":act_user,
        "alert_dic":alert_dic,
        "today":datetime.date.today().strftime("%Y-%m-%d"),
        "modal_sort":request.session["modal_sort"],
    }

    return render(request,"crm/alert.html",params)


# アラート表_検索
def alert_search(request):
    request.session["alert_month"]=request.POST["alert_month"]
    return redirect("crm:alert_index")



# 顧客最終履歴
@login_required
def contact_index(request):
    if "contact_month" not in request.session:
        request.session["contact_month"]=datetime.datetime.now().strftime("%Y-%m")

    contact_month=request.session["contact_month"]
    contact_dic=make_dic(contact_month)

    tantou_id=request.session["tantou_id"]
    cus_act=set(Crm_action.objects.filter(tantou_id=tantou_id,type__in=[1,2,4,5]).values_list("cus_id",flat=True).order_by("cus_id").distinct())
    cus_est_all=list(Sfa_data.objects.filter(tantou_id=tantou_id).values_list("cus_id",flat=True).order_by("cus_id").distinct())
    cus_est_month=set(Customer.objects.filter(cus_id__in=cus_est_all,update_last_day__startswith=contact_month).values_list("cus_id",flat=True).order_by("cus_id").distinct())
    cus_list=list(cus_act | cus_est_month)
 
    for i in cus_list:
        ins=Customer.objects.get(cus_id=i)
        ins2=Sfa_data.objects.get(mitsu_num=ins.update_last_num,mitsu_ver=ins.update_last_ver)
        ins3=Crm_action.objects.filter(cus_id=i,type__in=[1,2,4,5]).order_by("day","act_id").reverse()
        
        dic={
            "cus_id":i,
            "cus_url":ins.cus_url,
            "cus_com":ins.com,
            "cus_sei":ins.sei,
            "cus_mei":ins.mei,
            "est_last":ins.update_last_day[:10],
            "est_status":ins2.s_status,
            "est_num":ins2.mitsu_num,
            "est_ver":ins2.mitsu_ver,
            "est_url":ins2.mitsu_url,
            "est_kubun":ins2.order_kubun,
            "est_money":ins2.money,
            }
        
        if ins3.count()==0:
            dic["day"]=ins.update_last_day[:10]

        elif max(ins3[0].day[:7],ins.update_last_day[:7])==contact_month:
            dic["day"]=max(ins3[0].day,ins.update_last_day[:10])
            dic["act_day"]=ins3[0].day
            dic["act_type"]=ins3[0].type
            dic["act_text"]=ins3[0].text

        else:
            continue

        contact_dic[dic["day"]]["text_all"].append(dic)

    
    # 操作者
    sousa_time=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    sousa_busho=Member.objects.get(tantou_id=tantou_id).busho
    sousa_tantou=Member.objects.get(tantou_id=tantou_id).tantou
    act_user=Member.objects.get(tantou_id=tantou_id).tantou
    print(sousa_time,sousa_busho,sousa_tantou,"■ 顧客最終履歴")

    params={
        "contact_month":contact_month,
        "act_user":act_user,
        "contact_dic":contact_dic,
        "modal_sort":request.session["modal_sort"],
    }

    return render(request,"crm/contact.html",params)


# 顧客最終履歴_検索
def contact_search(request):
    request.session["contact_month"]=request.POST["contact_month"]
    return redirect("crm:contact_index")


# FUNC カレンダー作成
def make_dic(select_month):
    y=int(select_month[:4])
    m=int(select_month[-2:])

    ins=calendar.monthrange(y,m)
    last_day=ins[1]

    select_dic={}
    we_dic={0:"月",1:"火",2:"水",3:"木",4:"金",5:"土",6:"日",}
    for i in range(1,last_day+1):
        day=datetime.date(y,m,i)
        week=we_dic[day.weekday()]

        if jpholiday.is_holiday(day):
            week_color="2"
        elif week == "土":
            week_color="1"
        elif week == "日":
            week_color="2"
        else:
            week_color="0"

        select_dic[day.strftime("%Y-%m-%d")]={"week":week,"week_color":week_color,"text_all":[]}

    return select_dic

sfa_crm_fc/crm/templates/crm/alert.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="icon" href="{% static 'whale.gif' %}">
    <title>アラート設定表</title>
</head>
<body>

    <div class="mt-3 mb-5">

        <!-- メニュー -->
        <div style="margin: 0 auto; width: 1100px">
            {% include "sfa/menu.html" with act_user=act_user %}
        </div>

        <div style="margin: 0 auto; width: 1100px;">
            <hr>
            <div class="block_title">アラート設定表</div>
            <hr>

            <!-- フィルター -->
            <div>
                <form action="{% url 'crm:alert_search' %}" method="post">{% csrf_token %}                    
                    <div class="flex mt-4">
                        <div>対象月：</div>
                        <div><input class="form-control" type="month" name="alert_month" value="{{alert_month}}"></div>
                        <div style="margin-left: 20px;"><button type="submit" class="btn btn-secondary"><i class="bi bi-search"></i> 検索</button></div>
                    </div>
                </form>    
            </div>
            <hr>

            <!-- 設定表 -->
            <div>
                {% for k,v in alert_dic.items %}
                
                    {% if k == today %}
                    <div class="flex al_main" style="flex-wrap: nowrap; background-color: #ffff00;">
                    {% else %}
                    <div class="flex al_main" style="flex-wrap: nowrap;">
                    {% endif %}

                        {% if v.week_color == "1" %}
                        <div style="width: 180px; color: blue;">
                        {% elif v.week_color == "2" %}
                        <div style="width: 180px; color: red;">
                        {% else %}
                        <div style="width: 180px;">
                        {% endif %}
                        {{k}}（{{v.week}}）
                        </div>

                        <div style="width: 100%;">
                            {% for h in v.text_all %}

                                <!-- 解除済みの場合 -->
                                {% if h.check == 1 %}
                                <div class="flex3 al_sub al_s2">
                                    <div class="flex">
                                        <div style="width: 40px;"><i class="bi bi-bell-slash-fill"></i></div>
                                        <div style="width: 200px;">{% if h.cus.com %}{{h.cus.com | truncatechars:14}}{% endif %}</div>
                                        <div style="width: 150px;">
                                            {% if h.cus.sei %}{{h.cus.sei}}{% endif %}
                                            {% if h.cus.mei %}{{h.cus.mei}}{% endif %}
                                        </div>
                                        <div style="width: 450px;">{{h.text}}</div>
                                    </div>
                                <!-- 現在設定中 -->
                                {% else %}
                                <div class="flex3 al_sub al_s1">
                                    <div class="flex">
                                        <div style="width: 40px;"><i class="bi bi-alarm"></i></div>
                                        <div style="width: 200px;">{% if h.cus.com %}{{h.cus.com | truncatechars:14}}{% endif %}</div>
                                        <div style="width: 150px;">
                                            {% if h.cus.sei %}{{h.cus.sei}}{% endif %}
                                            {% if h.cus.mei %}{{h.cus.mei}}{% endif %}
                                        </div>
                                        <div style="width: 450px; color: #ff0000;">{{h.text}}</div>
                                    </div>
                                {% endif %}
   
                                    <div style="width: 40px;">
                                        <button type="button" class="btn btn-outline-secondary btn-sm" style="border-radius: 50%;"  id="modal_{{h.cus.cus_id}}" name="cus_list"
                                            data-bs-toggle="modal" data-bs-target="#modal_cus">
                                            <i class="bi bi-pencil-square"></i>
                                        </button>
                                    </div>

                                </div>

                            {% endfor %}
                        </div>

                    </div>

                {% endfor %}
            </div>

        </div>

        <!-- モーダル -->
        {% include "sfa/modal_code.html" %}

    </div>
    

    <!-- 各種Ajax -->
    <script>

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i <cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
  
        var csrftoken = getCookie('csrftoken');
  
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
  
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });


    </script>

    <!-- モーダル_script -->
    {% include "sfa/modal_script.html" %}
    

</body>
</html>

sfa_crm_fc/crm/templates/crm/contact.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="icon" href="{% static 'whale.gif' %}">
    <title>顧客最終履歴</title>
</head>
<body>

    <div class="mt-3 mb-5">

        <!-- メニュー -->
        <div style="margin: 0 auto; width: 1100px">
            {% include "sfa/menu.html" with act_user=act_user %}
        </div>

        <div style="margin: 0 auto; width: 1100px;">
            <hr>
            <div class="block_title">顧客最終履歴</div>
            <hr>

            <!-- フィルター -->
            <div>
                <form action="{% url 'crm:contact_search' %}" method="post">{% csrf_token %}                    
                    <div class="flex mt-4">
                        <div>対象月：</div>
                        <div><input class="form-control" type="month" name="contact_month" value="{{contact_month}}"></div>
                        <div style="margin-left: 20px;"><button type="submit" class="btn btn-secondary"><i class="bi bi-search"></i> 検索</button></div>
                    </div>
                </form>    
            </div>
            <hr>

            <!-- 設定表 -->
            <div>
                {% for k,v in contact_dic.items %}
                    <div class="flex al_main" style="flex-wrap: nowrap;">

                        {% if v.week_color == "1" %}
                        <div style="width: 180px; color: blue;">
                        {% elif v.week_color == "2" %}
                        <div style="width: 180px; color: red;">
                        {% else %}
                        <div style="width: 180px;">
                        {% endif %}
                        {{k}}（{{v.week}}）
                        </div>

                        <div style="width: 100%;">
                            {% for h in v.text_all %}

                                {% if h.est_status == "未" %}
                                <div class="flex3 cus_last_main" style="background-color: #FFF; align-items: center;">
                                {% elif h.est_status == "見" %}
                                <div class="flex3 cus_last_main" style="background-color: #ceffb7; align-items: center;">
                                {% elif h.est_status == "イ" %}
                                <div class="flex3 cus_last_main" style="background-color: #c8f7fd; align-items: center;">
                                {% elif h.est_status == "受" %}
                                <div class="flex3 cus_last_main" style="background-color: #fff9a7; align-items: center;">
                                {% elif h.est_status == "発" %}
                                <div class="flex3 cus_last_main" style="background-color: #dbbbff; align-items: center;">
                                {% elif h.est_status == "キ" %}
                                <div class="flex3 cus_last_main" style="background-color: #c5c5c5; align-items: center;">
                                {% elif h.est_status == "終" %}
                                <div class="flex3 cus_last_main" style="background-color: #ffbcbc; align-items: center;">
                                {% elif h.est_status == "保" %}
                                <div class="flex3 cus_last_main" style="background-color: #FFF; align-items: center;">
                                {% endif %}
                                    <div class="flex">
                                        <div style="width: 90px;">
                                            <a href="{{h.cus_url}}" target="_blank"><span style="color: #ff8484;"><i class="bi bi-box-arrow-up-right"></i></span></a>
                                            <span style="font-size: 0.9em;">{{h.cus_id}}</span>
                                        </div>
                                        <div style="width: 180px;">{% if h.cus_com %}{{h.cus_com | truncatechars:12}}{% endif %}</div>
                                        <div style="width: 140px;">
                                            {% if h.cus_sei %}{{h.cus_sei}}{% endif %}
                                            {% if h.cus_mei %}{{h.cus_mei}}{% endif %}
                                        </div>
                                        <div style="width: 450px;">
                                            <div class="flex">
                                                <div style="width: 40px;"><div class="order_use">{{h.est_status}}</div></div>
                                                <div style="width: 110px;">{{h.est_last}}</div>
                                                <div style="width: 120px;">
                                                    <a href="{{h.est_url}}" target="_blank"><span style="color: #008b8b;"><i class="bi bi-box-arrow-up-right"></i></span></a>
                                                    <span style="font-size: 0.9em;">{{h.est_num}}-{{h.est_ver}}</span>
                                                </div>
                                                <div style="width: 80px;">{{h.est_kubun}}</div>
                                                <div>{{h.est_money | intcomma}}円</div>
                                            </div>

                                            {% if h.act_day %}
                                            <hr style="margin: 5px 0px;">
                                            <div class="flex">
                                                <div style="width: 40px; padding-left: 5px;">
                                                    {% if h.act_type == 1 %}
                                                    <span style="color: #0000ff; font-weight: bold;"><i class="bi bi-telephone-forward-fill"></i></span>
                                                    {% elif h.act_type == 2 %}
                                                    <span style="color: #ff9900; font-weight: bold;"><i class="bi bi-envelope-fill"></i></span>
                                                    {% elif h.act_type == 4 %}
                                                    <span style="color: #ff3502; font-weight: bold;"><i class="bi bi-shop"></i></span>
                                                    {% elif h.act_type == 5 %}
                                                    <span style="color: #00c2b8; font-weight: bold;"><i class="bi bi-people-fill"></i></span>
                                                    {% endif %}
                                                </div>
                                                <div style="width: 110px;">{{h.act_day}}</div>
                                                <div style="width: 295px;">{{h.act_text}}</div>
                                            </div>
                                            {% endif %}

                                        </div>
                                    </div>
                                    <div style="width: 40px;">
                                        <button type="button" class="btn btn-outline-secondary btn-sm" style="border-radius: 50%;"  id="modal_{{h.cus_id}}" name="cus_list"
                                            data-bs-toggle="modal" data-bs-target="#modal_cus">
                                            <i class="bi bi-pencil-square"></i>
                                        </button>
                                    </div>

                                </div>

                            {% endfor %}
                        </div>

                    </div>

                {% endfor %}
            </div>

        </div>

        <!-- モーダル -->
        {% include "sfa/modal_code.html" %}

    </div>
    

    <!-- 各種Ajax -->
    <script>

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i <cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
  
        var csrftoken = getCookie('csrftoken');
  
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
  
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });


    </script>

    <!-- モーダル_script -->
    {% include "sfa/modal_script.html" %}
    

</body>
</html>